### ISSUE TITLE
Scenario Edit mode "Wrench icon" tool tip is missing

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#44]
![edit_tooltip](https://user-images.githubusercontent.com/308490/31671044-492b26ce-b359-11e7-8096-5c139f1a90b3.png)

Refer to attached screen shot.
- do mouse over wrench icon
- tool tip is missing

**Comment by cbliard** [comment]
Which tool tip are you missing exactly? I guess it's one that explains what will happen if you click on it, or maybe it's a label about what the wrench means.

**Comment by vikramvi** [comment]
yes; the label which should explain to user what "wrench" icon means or suppose to do ?

**Comment by cbliard** [comment]
That makes perfectly sense. Thank you for reporting it.

**Comment by jracenet** [comment]
Hey @vikramvi 
This one should be fixed too!
I think we will later change these icons simply by their textual equivalent ('action' / 'result'), or make the toggle more explicit.

Thanks for the feedback!

**Comment by vikramvi** [comment]
@jracenet can you please re-open as below related issues still present

- Wrench icon now shows tool tip as "Action" but it's not obvious what it means ?
- adding "?" to give detailed info can be useful
- Refer to 2 attached screen shot
- first one puzzle icon doesn't have tool tip
- second one; clicking on Given button opens menu option; this flow is not pretty obvious or confusing
- What use suppose to do clicking on button ?

![button](https://user-images.githubusercontent.com/308490/31814384-c0377952-b589-11e7-99e8-2d90626692f5.png)
![wrench_icon](https://user-images.githubusercontent.com/308490/31814385-c0525d1c-b589-11e7-9f8f-c59e75f08fa3.png)

**Comment by jracenet** [comment]
Hi @vikramvi,

> Wrench icon now shows tool tip as "Action" but it's not obvious what it means ?
> What use suppose to do clicking on button ?

These two issues will be addressed at the same time than issue #57:

* The "Action" and "Results" steps are not supposed to be used when writing scenarios using Gherkin syntax. Please activate the BDD mode in your project settings (note that this will not "convert" the action/results steps into an equivalent Gherkin step).

* A redesign of the step type toggle  should answer to these UX issues (use of a menu like the Given/When/Then selector)

> adding "?" to give detailed info can be useful

* We are going to experiment interactive tooltips in the coming iteration, and add some progressively in few points of the application

> Refer to 2 attached screen shot
> first one; puzzle icon doesn't have tool tip
> second one; clicking on Given button opens menu option; this flow is not pretty obvious or confusing

* Our intention is to also use a menu for the classic action/result steps

**Comment by vikramvi** [comment]
@jracenet 
- IMHO asking user to activate "BDD mode" is kind of confusing as user is using hiptest for achieving BDD then why s/he needs to activate this explicitly ?
- I am finding it quite confusing and hard to understand
- "The "Action" and "Results" steps are not supposed to be used when writing scenarios using Gherkin syntax. " ,  not sure if new user will understand different between Gerhkin mode vs BDD mode ?
- Also if particular feature is not supposed to be used in particular mode then it should be in disabled state
- I'm super confused now :)
- please get feedback on this flow from other users as well

**Comment by jracenet** [comment]
@vikramvi You're absolutely right! Actually, it's all about bad wording:

* What we call "BDD mode" in project settings is more a "Gherkin syntax support" mode. When you activate it, all your steps are created as action words and are prefixed when Gherkin keywords Given/When/Then. When the mode is set to off, your steps are type with classic "action/results" philosophy, and it is used by users that don't write their steps using the Gherkin syntax. It would be far more user friendly if all of that was explained at the project creation. Plus, all of our users are not using Hiptest with BDD philosophy :-)

* When the "Gherkin syntax support" mode (aka. "BDD mode" in the current project settings) is activated, you can't create action/result steps. But, if your scenarios are written with these before setting the mode to 'on', we didn't want to 'auto-convert' them into Gherkin syntax, to avoid bad conversions, so that's why they may still appear.

* The current control need a redesign to be visible indeed. I was just talking about the idea of a menu more than a simple button that have a pretty unpredictable behaviour :))

I hope that will help you to be less confuse :D

**Comment by vikramvi** [comment]
@jracenet Thanks a ton for your answers with lots of patience :)

**Comment by jracenet** [comment]
@vikramvi You're welcome, thank you for your commitment to the improvement of the quality of our platform :)
It means that we have a lot to do to make all of that really understandable and user friendly.

**Comment by cbliard** [comment]
Hi @vikramvi 

Can we close this one?
